In [3]:
import random

x = random.randrange(10)
x


0

In [4]:
random.randint(1,10)


9

In [6]:
d1 = dict(a=3,b=12,ab=34)

d1

{'a': 3, 'b': 12, 'ab': 34}

In [8]:
dict(a=5,b=7)

{'a': 5, 'b': 7}

In [9]:
a = '''abcd'''
a

'abcd'

In [7]:
a = 'banana','guava'
print(a,type(a))

('banana', 'guava') <class 'tuple'>


In [11]:
for i in a:
    print(i)

banana
guava


In [12]:
for i in a:
    for j in i:
        print(j)

b
a
n
a
n
a
g
u
a
v
a


In [13]:
len(a)

2

In [14]:
x = "hello nice to see you!!"
'see' in x

True

In [27]:
d = "Hello Team, good morning"

d[3:5]

'lo'

In [16]:
d[1:5:2]

'el'

In [17]:
d[0:7:3]

'HlT'

In [18]:
d[::-1]

'gninrom doog ,maeT olleH'

In [19]:
d[-1]

'g'

In [20]:
d[:-1]

'Hello Team, good mornin'

In [21]:
d[:-3]

'Hello Team, good morn'

In [22]:
d[0:-3]

'Hello Team, good morn'

In [31]:
d[-6:-3]

'orn'

In [33]:
d.upper()

'HELLO TEAM, GOOD MORNING'

In [34]:
d.lower()

'hello team, good morning'

In [37]:
d.strip('T')

'Hello Team, good morning'

In [38]:
d.replace('T','Cr')

'Hello Cream, good morning'

In [39]:
d.split()

['Hello', 'Team,', 'good', 'morning']

In [40]:
d.split(',')

['Hello Team', ' good morning']

In [41]:
d+x

'Hello Team, good morninghello nice to see you!!'

In [42]:
d + ' ' + x

'Hello Team, good morning hello nice to see you!!'

In [45]:
x = 'John'
age = 32
print("The name of the person is {} whose age is {}".format(x,age))

The name of the person is John whose age is 32


In [46]:
print("The entire statement is {} with added on {}".format(d,x))

The entire statement is Hello Team, good morning with added on John


In [47]:
print(f"the name is {x} where age is {age}")

the name is John where age is 32


In [51]:
x = 'Hi I\'m  Bhawana'
x

"Hi I'm  Bhawana"

In [54]:
x = "This is the \"so called\" box"
x

'This is the "so called" box'

In [56]:
x = "This is the \\so called box"
x

'This is the \\so called box'

In [61]:
x = "Hello \bWorld"
print(x)

Hello World


In [59]:
#This example erases one character (backspace):
txt = "Hello \bWorld!"
print(txt)

Hello World!


In [62]:
txt.index("Hello")

0

In [63]:
class myclass():
  def __len__(self):
    return 0

myobj = myclass()
print(bool(myobj))

False


In [64]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

['cherry', 'orange', 'kiwi']


In [65]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[:4])

['apple', 'banana', 'cherry', 'orange']


In [66]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:])

['cherry', 'orange', 'kiwi', 'melon', 'mango']


In [67]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[-4:-1])

['orange', 'kiwi', 'melon']


In [68]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
thislist[1:3] = ["blackcurrant", "watermelon"]
print(thislist)

['apple', 'blackcurrant', 'watermelon', 'orange', 'kiwi', 'mango']


In [69]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)

['apple', 'banana', 'watermelon', 'cherry']


In [70]:
thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]
thislist.extend(tropical)
print(thislist)

['apple', 'banana', 'cherry', 'mango', 'pineapple', 'papaya']


In [71]:
thislist = ["apple", "banana", "cherry"]
thistuple = ("kiwi", "orange")
thislist.extend(thistuple)
print(thislist)

['apple', 'banana', 'cherry', 'kiwi', 'orange']


In [72]:
thislist = ["apple", "banana", "cherry"]
thislist.pop(1)
print(thislist)

['apple', 'cherry']


In [73]:
thislist.pop()

'cherry'

In [76]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]

for i in range(len(thislist)):
    print(thislist[i])

apple
banana
cherry
orange
kiwi
mango


In [1]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]
i=0

while i< len(thislist):
    print(thislist[i])
    i=i+1

apple
banana
cherry
orange
kiwi
mango


In [7]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]

x = [print(i*2) for i in (thislist)]
x

appleapple
bananabanana
cherrycherry
orangeorange
kiwikiwi
mangomango


[None, None, None, None, None, None]

In [8]:
newlist = [i for i in thislist]
newlist

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'mango']

In [9]:
newlist = [i*2 for i in thislist]
newlist

['appleapple',
 'bananabanana',
 'cherrycherry',
 'orangeorange',
 'kiwikiwi',
 'mangomango']

In [10]:
newlist = [i for i in thislist if i!='apple']
newlist

['banana', 'cherry', 'orange', 'kiwi', 'mango']

In [2]:
newlist = [i if i%2 == 0 else 0 for i in range(10)]
newlist

[0, 0, 2, 0, 4, 0, 6, 0, 8, 0]

In [14]:
newlist= [i if i=='banana' else 'orange'for i in thislist]
newlist

['orange', 'banana', 'orange', 'orange', 'orange', 'orange']

In [19]:
newlist = [i if i%2==0 else 3 for i in range(10) ]
newlist

[0, 3, 2, 3, 4, 3, 6, 3, 8, 3]

In [21]:
x = ["abc","ABC","aABc"]
[print(i) for i in x if 'a' in i]

abc
aABc


[None, None]

In [22]:
thislist = ["banana", "Orange", "Kiwi", "cherry"]
thislist.sort(key = str.lower)
print(thislist)

['banana', 'cherry', 'Kiwi', 'Orange']


In [23]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

for x in list2:
  list1.append(x)

print(list1)

['a', 'b', 'c', 1, 2, 3]


In [24]:
thistuple = ("apple",)
print(type(thistuple))

#NOT a tuple
thistuple = ("apple")
print(type(thistuple))

<class 'tuple'>
<class 'str'>


In [25]:
tup1 = (1,2,[3,4,5],6)
tup1

(1, 2, [3, 4, 5], 6)

In [26]:
type(tup1)

tuple

In [27]:
x = tup1[2]
type(x)

list

In [28]:
y = [2,5j,6]
y.sort()


TypeError: '<' not supported between instances of 'complex' and 'int'

In [30]:
set1 = {1,2,3,4,5,5,5,(1,2,3,4)}
set1

{(1, 2, 3, 4), 1, 2, 3, 4, 5}

In [31]:
thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)

{'cherry', 'orange', 'banana', 'apple'}


In [33]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.intersection_update(y)

print(z)

None


In [34]:
def cubefunc(x):
    return x**3

x = [1,2,3,4,5]

print(list(map(cubefunc,x)))

[1, 8, 27, 64, 125]


In [5]:
class Animal():
    def __init__(self,name,breed):
        self.name = name
        self.breed = breed
    def printfunc(self,name,breed):
        print(name + " is a " +breed)
class Dog(Animal):
    def __init__(self,jump):
        self.jump = jump
        super().__init__(name,breed)
    def printfunc(self):
        print(Name + "who is" + breed + "can" + jump)
            
        

In [6]:
dog1 = Animal('pluto','pitbull')
dog1.printfunc('pluto','pitbull')

pluto is a pitbull


In [41]:
thisdict = {
  "brand": "Ford",
  "electric": False,
  "year": 1964,
  "colors": ["red", "white", "blue"]
}

for i in thisdict:
    print(i)
    print(thisdict[i])

brand
Ford
electric
False
year
1964
colors
['red', 'white', 'blue']


In [45]:
thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
for x, y in thisdict.items():
  print(x, y)

brand Ford
model Mustang
year 1964


In [47]:
def my_func(fname):
    print(fname+" sharma ")
my_func("Firi")

Firi sharma 


In [70]:
def new_func(*x):
    return(x)

import numpy as np
arr1 = np.array

In [71]:
new_func([1,2,3,4])

([1, 2, 3, 4],)

In [74]:
def new_func(**n):
    print(n[3]+n[6])

In [9]:
def fact(x):
    if x==1:
        return x
    else:
        return x*fact(x-1)

In [10]:
print(fact(6))

720


In [11]:
x = int(input())
n = 1
for i in range(1,x+1):
    n*=i
print(n)
    

7
5040


In [15]:
import numpy as np
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [16]:
type(arr1)

numpy.ndarray

In [18]:
arr1.shape

(4,)

In [19]:
arr1.ndim

1

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [24]:
np.random.random(5)

array([0.27457219, 0.9677171 , 0.84360166, 0.41732949, 0.2748197 ])

In [27]:
d = np.array([1,2,3,4])
s = np.array([4,5,6,7])

d/s

array([0.25      , 0.4       , 0.5       , 0.57142857])

In [28]:
d*s

array([ 4, 10, 18, 28])

In [29]:
d**s

array([    1,    32,   729, 16384], dtype=int32)

In [32]:
x= np.array([[1,2],[2,3]])

In [33]:
x

array([[1, 2],
       [2, 3]])

In [34]:
x[1][1]

3

In [36]:
x = np.array([[[[[[1,2,3,4]]]]]])
x

array([[[[[[1, 2, 3, 4]]]]]])

In [38]:
x.ndim

6

In [39]:
x.shape

(1, 1, 1, 1, 1, 4)

In [43]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [47]:
np.identity((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.eye(5,k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [53]:
np.random.randint(1,10,7)

array([2, 3, 6, 4, 8, 5, 5])

In [57]:
x = np.random.randint(1,20,(3,4))
x


array([[ 2,  7, 13, 12],
       [13,  6, 15, 15],
       [18, 11, 10, 13]])

In [59]:
x.reshape(6,2)

array([[ 2,  7],
       [13, 12],
       [13,  6],
       [15, 15],
       [18, 11],
       [10, 13]])

In [61]:
x = 1

while x<=10:
    print(x)
    x+=1

1
2
3
4
5
6
7
8
9
10


In [62]:
x = [10,22.2,33.4,12.3,13.1,11]

for i in x:
    if i%2==0:
        print(i)

10


In [66]:
x = [1,2,3,4,5,6,7,8,9,10]

newlist = [i for i in x if i%2==0]
newlist

[2, 4, 6, 8, 10]

In [67]:
x = int(input("Enter the size of array"))
arr = i for i in range(x)


Enter the array,if done enter end1


TypeError: array() missing required argument 'object' (pos 0)

In [82]:
class Animal():
    def __init__(self, name):
        self.name = name
    
    
class Dog(Animal):
    def say(self):
        return "woof"

class Cat(Animal):
    def say(self):
        return "Meow"
    
        

In [88]:
animals = [Dog("Frido"),Cat("Billu"),Dog("Pluto")]

for i in animals:
    print(i.name + "says"+ i.say())

Fridosayswoof
BillusaysMeow
Plutosayswoof


In [14]:
class Numclass():
    def __init__(self,a):
        self.a = a
    def num1(self):
        return self.a
        

In [15]:
a1 = Numclass(2)
a1.num1()

2

In [20]:
class simple():
    
    def num(self):
        return 3

In [21]:
b = simple()
print(b.num())

3


In [22]:
print(b.num())

3


In [26]:
class Computr():
    def config(self):
        print("6gb","4mb")

In [27]:
cmp = Computr()

In [28]:
cmp.config()

6gb 4mb


In [32]:
class Computer():
    def __init__(self,cpu,ram):
        self.cpu = cpu
        self.ram = ram
    def config(self):
        print(self.cpu + " has " + self.ram)

In [33]:
comp1 = Computer("intel core","32gb")

In [34]:
comp1.config()

intel core has 32gb


In [36]:
class mobile():
    camp ="This is a mobile"
    print(camp)
    def __init__(self,name,colour):
        self.name = name
        self.colour = colour
    def mob(self,camp):
        print(camp)
        print(self.name)
    def col(self,camp):
        print(camp)
        print(self.colour)

This is a mobile


In [37]:
m1 = mobile("Redmi10","Blue")
m1.mob("new mobile")

new mobile
Redmi10


In [38]:
m1.col("old mobile")

old mobile
Blue


In [130]:
mobile.camp

'This is a mobile'

In [39]:
class Parent():
    def __init__(self):
        self.name = "Anglo"
        self.age = "12"
class Child(Parent):
    def par_name(self):
        print(self.name,self.age)

In [139]:
ch1 = Child()

In [140]:
ch1.par_name()

Anglo 12


In [148]:
n = "john"

print("The name is %s "%(n))

The name is john 


In [40]:
def add_one(func):
    def wrapper(*args, **kwargs):
        result = func(*args, **kwargs)
        return result + 1
    return wrapper

@add_one
def multiply(a, b):
    return a * b

print(multiply(2, 3))  # Output: 7

7


In [41]:
def myfunc(newfunc):
    def difffunc(x,y):
        result = newfunc(x,y)
        return result*2
    return difffunc
@myfunc

def diff(a,b):
    return a-b

In [49]:
def mainfunc(f1):
    def wrapping(x,y):
        print("Division of two numbers")
        result = f1(x,y)
        print("Value given below")
        return result
        
    return wrapping


@mainfunc
def division(a,b):
    return a//b

In [50]:
division(15,4)

Division of two numbers
Value given below


3

In [156]:
diff(7,3)

8

In [159]:
import re

txt = "This is raining"

x = re.search("is",txt)


<re.Match object; span=(2, 4), match='is'>

In [160]:
import re

txt = "This is raining"

x = re.findall("is",txt)
x


['is', 'is']

In [162]:
import re

txt = "The rain in Spain"
x = re.split(" ", txt)
print(x)

['The', 'rain', 'in', 'Spain']


In [163]:
import re

txt = "The rain in Spain"
x = re.sub("\s", "9", txt)
print(x)

The9rain9in9Spain


In [165]:
try:
  print(y)
except:
  print("An exception occurred")

An exception occurred


In [169]:
x = 12
y = 0

try:
    x/y
except Exception as e:
    print(e)

division by zero


In [170]:
try:
  print("Hello")
except:
  print("Something went wrong")
else:
  print("Nothing went wrong")

Hello
Nothing went wrong


In [171]:
try:
  print(x)
except:
  print("Something went wrong")
finally:
  print("The 'try except' is finished")

12
The 'try except' is finished


In [172]:
x = -1

if x < 0:
  raise Exception("Sorry, no numbers below zero")

Exception: Sorry, no numbers below zero

In [183]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\prac.txt","r")
for x in f:
    print(x)

Hello! Welcome to demofile.txt

This file is for testing purposes.

Good Luck!


In [182]:
print(f.read(5))

In [184]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\prac.txt","a")
f.write("A new text")
f.close()

In [186]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\prac.txt","r")
print(f.read())

Hello! Welcome to demofile.txt
This file is for testing purposes.
Good Luck!A new text


In [187]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\prac.txt","w")
f.write("Entire data is replaced")
f.close()

In [188]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\prac.txt","r")
print(f.read())

Entire data is replaced


In [189]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\newfile.txt","x")

In [191]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\newfile.txt","w")
f.write("This is a new file created through python \n the data it carries is just for practice")
f.close()

In [192]:
f = open(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\newfile.txt","r")
print(f.read())

This is a new file created through python 
 the data it carries is just for practice


In [198]:
import os

os.remove(r"C:\Users\bhawansa\OneDrive - AMDOCS\Backup Folders\Desktop\INTELLIPAAT Notes\prac.txt")

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\bhawansa\\OneDrive - AMDOCS\\Backup Folders\\Desktop\\INTELLIPAAT Notes\\prac.txt'

In [201]:
class Fruit():
    def __init__(self):
        print("I am fruit")
class Citrus(Fruit):
    def __init__(self):
        super().__init__()
        print("This is citrus")

In [202]:
lemon = Citrus()

I am fruit
This is citrus


In [220]:
class Fruit():
  
    def __len__(self):
        x = [10,20,30]
        return x
        
print(len(Fruit()))

TypeError: 'list' object cannot be interpreted as an integer

In [214]:
f1 = Fruit("Kawasaki")


TypeError: __len__() missing 1 required positional argument: 'a'

In [234]:
class A:
    x=1
class B(A):
    y=2
class C(B):
    
    pass

In [227]:
obj1 = A()

In [228]:
obj1.x

1

In [229]:
obj2=B()
obj2.x

1

In [230]:
obj2.y

2

In [236]:
obj3 = C()
obj3.x

1

In [237]:
class Parent1:
    def __init__(self):
        self.value1 = "I am Parent1"

class Parent2:
    def __init__(self):
        self.value2 = "I am Parent2"

class Child(Parent1, Parent2):
    def __init__(self):
        Parent1.__init__(self)
        Parent2.__init__(self)
        self.value3 = "I am Child"

c = Child()
print(c.value1)
print(c.value2)
print(c.value3)

I am Parent1
I am Parent2
I am Child


In [246]:
#mutiple inheritance

class P1():
    def __init__(self):
        self.val1 = "I am a Parent  1 class"
        
class P2():
    def __init__(self):
        self.val2 = "I am Parent 2 class"
        
class C(P1,P2):
    def __init__(self):
        P1.__init__(self)
        P2.__init__(self)
        C.val = "I am a child multiple inheritance from 2 parent  class P1 & P2"

In [240]:
c1= C()

In [241]:
c1.val1

'I am a Parent  1 class'

In [242]:
c1.val2

'I am Parent 2 class'

In [245]:
c1.val

'I am a child multiple inheritance from 2 parent  class P1 & P2'

In [252]:
class G():
    def __init__(self):
        self.name1 = "Grandparent"
class P(G):
    def __init__(self):
        super().__init__()
        self.name2 = "Parent"
class C(P):
    def __init__(self):
        super().__init__()
        self.name3 = "Child"
    def nam(self):
        print(self.name1,self.name2,self.name3)

In [253]:
c1 = C()

In [254]:
c1.name3

'Child'

In [255]:
c1.nam()

Grandparent Parent Child


In [256]:
class A:
    x = 1

class B(A):
    pass

class C(B):
    pass

In [257]:
c1 =C
c1.x

1

In [261]:
class A():
    def __init__(self,n1):
        self.n1 = n1
class B(A):
    def __init__self(self,n2):
        self.n2 = n2
        super().__init__(n1)
        print(self.n1,self.n2)

In [262]:
b1 = B("a")

In [263]:
b1.n1

'a'

In [264]:
def add(a,b):
    return a+b

def add(a,b,c):
    return a+b+c

In [266]:
add(2,3,4)

9

In [267]:
def add(*a):
    sum=0
    for i in a:
        sum+=i
    return sum
        

In [268]:
add(2,3,4,5)

14

In [270]:
#Overriding

class A():
    def sayhi(self):
        print("Class A")
class B(A):
    def sayhi(self):
        print("Class B")
        

In [271]:
b1 = B()

In [272]:
b1.sayhi()

Class B


In [273]:
a1=A()
a1.sayhi()

Class A


In [278]:
class A():
    def __init__(self,name):
        self.name =name
class B(A):
    def say(self):
        print("B",self.name)
class C(A):
    def say(self):
        print("C",self.name)

In [279]:
a1 = A("Dog")
b1 = B("Cat")
c1 = C("Owl")

In [280]:
a1.name

'Dog'

In [281]:
b1.say()

B Cat


In [282]:
c1.say()

C Owl


In [283]:
#Encapsulation 
class BankAccount:
    def __init__(self, balance=0):
        self.__balance = balance

    def get_balance(self):
        return self.__balance

    def deposit(self, amount):
        self.__balance += amount

    def withdraw(self, amount):
        if self.__balance >= amount:
            self.__balance -= amount
            return True
        else:
            return False

# creating an object of BankAccount
account = BankAccount(1000)

# checking the initial balance
print(account.get_balance())  # 1000

# making a deposit
account.deposit(500)

# checking the balance again
print(account.get_balance())  # 1500

# making a withdrawal
print(account.withdraw(1000))  # True

# checking the balance again
print(account.get_balance())  # 500

1000
1500
True
500


In [286]:
import seaborn as sns

titanic = sns.load_dataset("titanic")

In [287]:
titanic.corr()

survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500   
age        -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067   
sibsp      -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000   
adult_male -0.557080  0.094035  0.280328 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.198270 -0.584471 -0.583398 -0.271832   

            adult_male     alone  
survived     -0.557080 -0.203367  
pclass        0.094035  0.135207  
age           0.280328  0.198270  
sibsp        -0.253586 -0.584471  
parch        -0.349943 -0.583398  
fare         -0.182024 -0.271832  
adult_male    1.000000  0.404744  
alone         0.404744  1.000000

In [291]:
import matplotlib.pyplot as plt
plt.figure(figsize=(10,10))
sns.heatmap(titanic.corr(),annot= True)
plt.show()

In [292]:
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [293]:
sns.barplot(x = "sex",y ="fare",data = titanic)

<AxesSubplot:xlabel='sex', ylabel='fare'>

In [297]:
titanic[titanic['sex']=="male"].describe

<bound method NDFrame.describe of      survived  pclass   sex   age  sibsp  parch     fare embarked   class  \
0           0       3  male  22.0      1      0   7.2500        S   Third   
4           0       3  male  35.0      0      0   8.0500        S   Third   
5           0       3  male   NaN      0      0   8.4583        Q   Third   
6           0       1  male  54.0      0      0  51.8625        S   First   
7           0       3  male   2.0      3      1  21.0750        S   Third   
..        ...     ...   ...   ...    ...    ...      ...      ...     ...   
883         0       2  male  28.0      0      0  10.5000        S  Second   
884         0       3  male  25.0      0      0   7.0500        S   Third   
886         0       2  male  27.0      0      0  13.0000        S  Second   
889         1       1  male  26.0      0      0  30.0000        C   First   
890         0       3  male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town 

In [304]:
import pandas as pd
df = pd.Series([1,2,3,4,5],index = [1,2,3,4,5])
df

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [305]:
python -m pip install mysql-connector-python

SyntaxError: invalid syntax (1185458606.py, line 1)

In [13]:
#list of strings to find the most overlapping character

def overlapping_string(string):
    max_overlap = 0
    max_pair = ()
    
    for i in range(len(string)):
        for j in range(i+1,len(string)):
            overlap = len(set(string[i].intersection(string[j]))
            if overlap>max_overlap:
                max_overlap = overlap
                max_pair = (string[i],string[j])
    return max_pair
                          
    
                          
                    
            
            
    

SyntaxError: invalid syntax (2827675244.py, line 10)

In [14]:
def overlapping_strings(strings):
    max_overlap = 0
    max_pair = ()
    for i in range(len(strings)):
        for j in range(i+1, len(strings)):
            overlap = len(set(strings[i]).intersection(strings[j]))
            if overlap > max_overlap:
                max_overlap = overlap
                max_pair = (strings[i], strings[j])
    return max_pair

# Example usage
strings = ['hello', 'world', 'python', 'programming']
max_pair = overlapping_strings(strings)
print(max_pair) # Output: ('hello', 'world')

('python', 'programming')


In [51]:
X = 10.5

print(x)

NameError: name 'x' is not defined

In [52]:
try:
    X=10.5
    print(x)
except NameError:
    print("name \"x\" not defined")

name "x" not defined


In [53]:
a = 10
b =10.5
c  = b #c=10.5
b = a #b = 10
a = c #a=10.5

print("a = ",a, "b = ",b)

#swapping numbers 

a =  10.5 b =  10


In [55]:
#anothermethod to swap numbers

a,b = 12,14
print("a = ",a, "b = ",b)
a,b=b,a

print("a = ",a, "b = ",b)

a =  12 b =  14
a =  14 b =  12


In [57]:
x = 243
y = 42%2 #0
z = x//243 #1
print(z,y)


1 0


In [63]:
a,b,c = (2,2,2)

print("Output 1:",(a+2<b*c))
print("Output 2:",(a-2<b*c))

Output 1: False
Output 2: True


In [64]:
print("Python\\tworld")

Python\tworld


In [65]:
print("Python\tworld")

Python	world


In [68]:
z = 987
z = z+243 #987+243
print(z) #

1230
